version: '3.6'

volumes:
  app-data:
  mongo-data:

services:
    instagrammer:
        tty: true
        image: instagrammer:latest
        build:
            context: .
            dockerfile: ./docker/inst.Dockerfile
        environment:
            - FLASK_APP=instagrammer
            - FLASK_ENV=development
            - FLASK_RUN_HOST=0.0.0.0
            - DATABASE_URL=sqlite:///$PWD/app.db
            - SECRET_KEY=verysecretkey
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_DB=instagrammer
        volumes:
          - app-data:$PWD/data/db
        ports:
            - 5000:5000
        networks:
            - instagrammer
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        container_name: "mongo"
        networks:
            - instagrammer
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - mongo-data:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quietmongo

networks:
    instagrammer:
        external: true