"""init

Revision ID: 1416f43927a6
Revises: 8e9c46887a13
Create Date: 2020-05-25 13:33:54.992350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1416f43927a6"
down_revision = "8e9c46887a13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_username", table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), nullable=True),
        sa.Column("password_hash", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_username", "user", ["username"], unique=1)
    # ### end Alembic commands ###
